version: '2.3'
services:
      db:
        container_name: db
        build: ./mysql_db
        environment:
            - DB_ALLOW_EMPTY_PASSWORD=yes
            - DB_ROOT_PASSWORD=pwd
        healthcheck:
            test: "exit 0"
        image: mysql
        ports: 
            - "3306:3306"
      
        networks:
            - rete
    
      serverjs:
          container_name: serverJS
          build:
            context: ./nodeJS_server/
            dockerfile: Dockerfile
          ports:
              - "8080:8080"
          environment:
              - DATABASE_HOST=db
          depends_on:
                db:
                  condition: service_healthy
          
          networks:
            - rete
            
networks:
    rete:
        driver: bridge
        
